apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: {{ .Values.servingRuntime.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    openshift.io/display-name: {{ .Values.servingRuntime.name }}
    opendatahub.io/accelerator-name: nvidia-gpu
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  labels:
    opendatahub.io/dashboard: "true"
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: {{ .Values.servingRuntime.port | quote}}
  containers:
    - name: kserve-container
      image: {{ .Values.servingRuntime.image }}
      args:
        - --host
        - 0.0.0.0
        - --port
        - {{ .Values.servingRuntime.port | quote}}
      {{- with .Values.servingRuntime.args }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-secret
              key: token
        - name: VLLM_CONFIG_ROOT
          value: /tmp/vllm
        - name: VLLM_CACHE_ROOT
          value: /tmp/vllm_cache
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
        - name: VLLM_TARGET_DEVICE
          value: cuda
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
      ports:
        - containerPort: {{ .Values.servingRuntime.port }}
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: {{ .Values.servingRuntime.modelFormat }}
